### ISSUE TITLE
analog mode

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVM#190]
Hello,

Is it possible to add analog mode support? We would like to use C4FM/DMR and analog mode as well.

Thank you.

**Comment by iddq** [comment]
can we talk about analog mode support?

**Comment by pedda4711** [comment]
Hello, multimode is possible with svxlink and mmdvm. Jonathan has integrated a patch last year, so that mmvmhost announce via a temporary file if digital ist active. I've also make patch vor svxlink, so svxlinks stop working, if digital is active and send cos-lockout if analog is active.
https://peges.de/afu/multimode/svxlink-lockout/

73' Peter, db1ofh

**Comment by iddq** [comment]
FM mode is supported now
