### ISSUE TITLE
MMDMV_POG don't work anymore

### ISSUE THREAD

**Issue by badtime** [g4klx/MMDVM#277]
Hi,

since from commit 8e52bdcc5c58cdf2e83b9319781ff49c2895c3f0 the MMDVM_POG don't work anymore.
When power up it start but no led staginng, the board still dead! Only PWR and the third led dimmed turn on.

The last working commit is 1332c6544b4bc4e8b6a0254b6d7fc0e4a1e3ee98

What's happened?

73 IZ8GUR

**Comment by yo6nam** [comment]
+1

I also reported this issue here :
https://groups.io/g/OpenDV/message/354

**Comment by badtime** [comment]
> +1
> I also reported this issue here :
> https://groups.io/g/OpenDV/message/354

Yes, but the lastest working is 1332c6544b4bc4e8b6a0254b6d7fc0e4a1e3ee98 already in the "FM era".

but also the last 7fabddd7f15162e28704682aeaee7c6f93e328b8 sill not working, and the sad thing is that none of the developing ones are interested at now.

**Comment by yo6nam** [comment]
Long story short, "POG" boards will not be supported anymore.
Have a read here : https://groups.io/g/OpenDV/message/367

**Comment by badtime** [comment]
Yes....ok.....I can understand this in the near future...but...one commit of may 13 work on the POG (with FM ecc.ecc.), and in the same day another commit with a merge don't work......i think is only bad coding from merge request that does not consider niche boards IMHO.

**Comment by yo6nam** [comment]
I don't really care about FM, although it would have been nice to make it work on repeaters already available, with just a FW upgrade. I just wish future development for the DMR will include support for the POG boards because I have plenty in use.

**Comment by g4klx** [comment]
Please tell me which commit actually broke your board. I need the commit id, and I'll see what I can do.
    On Friday, 29 May 2020, 16:12:09 BST, badtime <notifications@github.com> wrote:  
 
 


Yes....ok.....I can understand this in the near future...but...one commit of may 13 work on the POG (with FM ecc.ecc.), and in the same day another commit with a merge don't work......i think is only bad coding from merge request that does not consider niche boards IMHO.

**Comment by g4klx** [comment]
I think it would also be very nice if SP6POG took responsibility for maintaining hos code. If I can't fix it, and if he doesn't step in to help, then I will delete the POG code from the MMDVM. I don't like people creating things that I can't maintain.
    On Friday, 29 May 2020, 16:23:51 BST, yo6nam <notifications@github.com> wrote:  
 
 


I don't really care about FM, although it would have been nice to make it work on repeaters already available, with just a FW upgrade. I just wish future development for the DMR will include support for the POG boards because I have plenty in use.

**Comment by g4klx** [comment]
I've updated the master branch with an old version of the POG code from before the FM changes. I have no way of telling if its OK, but you can give it a try. If it doesn't work, contact SQ6POG.
    On Friday, 29 May 2020, 16:23:51 BST, yo6nam <notifications@github.com> wrote:  
 
 


I don't really care about FM, although it would have been nice to make it work on repeaters already available, with just a FW upgrade. I just wish future development for the DMR will include support for the POG boards because I have plenty in use.

**Comment by badtime** [comment]
No way....dont work!
So, but....what's changed in "Merge branch 'master' into FM 8e52bdcc5c58cdf2e83b9319781ff49c2895c3f0" ?? Because after this merge of 9 MAY the POG stop Working...only 14 commits ago...12 if we remove the 2 of today. This is a quite recent trouble after that merge, and is in that merge which must be investigated IMHO.

> 
> I've updated the master branch with an old version of the POG code from before the FM changes. I have no way of telling if its OK, but you can give it a try. If it doesn't work, contact SQ6POG. On Friday, 29 May 2020, 16:23:51 BST, yo6nam <notifications@github.com> wrote: I don't really care about FM, although it would have been nice to make it work on repeaters already available, with just a FW upgrade. I just wish future development for the DMR will include support for the POG boards because I have plenty in use. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by g4klx** [comment]
I give up!
Can you fix it then? None of the main developers have such a board for testing and the developer seems to have disappeared. What are we to do?
I do this as a hobby and I don’t like it when people create non-standard hardware and expect us to keep it running. It isn’t fair.
Please try and contact SQ6POG and get him to fix it. If it’s not done in one week, all POG support will be removed from the MMDVM permanently. Do you understand?
Please do not demand that I do ANYTHING.


Sent from Yahoo Mail for iPhone


On Monday, June 1, 2020, 17:26, badtime <notifications@github.com> wrote:




No way....dont work!
So, but....what's changed in "Merge branch 'master' into FM 8e52bdc" ?? Because after this merge of 9 MAY the POG stop Working...only 14 commits ago...12 if we remove the 2 of today. This is a quite recent trouble after that merge, and is in that merge which must be investigated IMHO.


I've updated the master branch with an old version of the POG code from before the FM changes. I have no way of telling if its OK, but you can give it a try. If it doesn't work, contact SQ6POG. On Friday, 29 May 2020, 16:23:51 BST, yo6nam notifications@github.com wrote: I don't really care about FM, although it would have been nice to make it work on repeaters already available, with just a FW upgrade. I just wish future development for the DMR will include support for the POG boards because I have plenty in use. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yo6nam** [comment]
Jonathan is right. Support for old hardware should be dropped (including Arduino which is also affected by the inclusion of FM code). The previous commits are stable enough to keep the POG boards in service with DMR/D-Star/C4FM.

Thanks for your time on this, Jonathan!

**Comment by badtime** [comment]
Ok....i've saved the alstest working commit....I will continue to use it until the firmware is obsolete.

Thanks a lot Jonathan for the time the time you spend for us.

i will try to contact SP6POG hoping for the best.

**Comment by shawnchain** [comment]
I'm pretty sure FM mode requires more ram than a F103/105 can provide. Please switch to F4 with 128K+ ram or wait for other work around appears.

**Comment by badtime** [comment]
Yes, it's true...but at this moment STM32F10X and the most powerful STM32F446 don't work anymore, both stop working after 1332c6544b4bc4e8b6a0254b6d7fc0e4a1e3ee98 so, I still don't think at now it's a performance issue.
At this point it would make sense to remove the support from all the other boards and leave only arduino two


> I'm pretty sure FM mode requires more ram than a F103/105 can provide. Please switch to F4 with 128K+ ram or wait for other work around appears.

**Comment by SA7BNT** [comment]
> Yes, it's true...but at this moment STM32F10X and the most powerful STM32F446 don't work anymore, both stop working after [1332c65](https://github.com/g4klx/MMDVM/commit/1332c6544b4bc4e8b6a0254b6d7fc0e4a1e3ee98) so, I still don't think at now it's a performance issue.
> At this point it would make sense to remove the support from all the other boards and leave only arduino two
> 
 Just updated MMDVM Firmware. Using STM32F446 and Toufik modem Version 1.1
Seems to working well.

**Comment by badtime** [comment]
What commit? 7fabddd7f15162e28704682aeaee7c6f93e328b8 or the last workaround 1 June?



> > Yes, it's true...but at this moment STM32F10X and the most powerful STM32F446 don't work anymore, both stop working after [1332c65](https://github.com/g4klx/MMDVM/commit/1332c6544b4bc4e8b6a0254b6d7fc0e4a1e3ee98) so, I still don't think at now it's a performance issue.
> > At this point it would make sense to remove the support from all the other boards and leave only arduino two
> 
> Just updated MMDVM Firmware. Using STM32F446 and Toufik modem Version 1.1
> Seems to working well.

**Comment by scotta1980** [comment]
the sp8nth board no longer works also is this one of the bords that no longer will be supported
